services:
  sftp: 
    image: atmoz/sftp:alpine-3.7
    ports: 
      - "2222:22"
    volumes:
      - ./users.conf:/etc/sftp/users.conf:ro
      - ./ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./students:/home/
    restart: unless-stopped
      
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./www:/usr/share/nginx/html:ro
      - ./students:/srv/students:ro
    ports:
      - "8080:80"
    restart: unless-stopped
